# Generated by Django 2.0.7 on 2018-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='decom_date',
            field=models.DateTimeField(),
        ),
    ]
