# Generated by Django 2.0.7 on 2018-07-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_prog',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='training_prog',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
