# Generated by Django 2.0.7 on 2018-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180730_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='decom_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
