# Generated by Django 2.0.7 on 2018-07-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20180726_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
