# Generated by Django 2.0.7 on 2018-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='API.Prod_Order', to='API.Product'),
        ),
    ]
