# Generated by Django 2.0.7 on 2018-07-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('decom_date', models.IntegerField(default=1)),
            ],
        ),
    ]
